# Binary Vocabulary file's path
FBoWVocabularyPath = 'E:\git_repos\ORB_SLAM2\Vocabulary\ORBvoc.bin'

# Path of images collection text
ImagesCollectionPath = 'E:\git_repos\ORB_SLAM2\Examples\Monocular\shenzhen_images.txt'

# Path of cameras pose collection text
CameraPoseCollectionPath = 'E:\git_repos\ORB_SLAM2\Examples\Monocular\shenzhen_cameras.txt'

# Path of ORB_SLAM2 configure file
ORBSLAMConfigPath = 'E:\git_repos\ORB_SLAM2\Examples\Monocular\shenzhen_simple.yaml'